management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
mongodb:
  database-name: weather
  connection-string: ""
  is-connection-secret: false

server:
  servlet:
    context-path: /weather
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false