springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
mongodb:
  database-name: weather
  connection-string: ""
  is-connection-secret: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

server:
  port: 8080