global:
  scrape_interval: 15s
  external_labels:
    monitor: 'weather-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'weather-platform'
    metrics_path: '/weather/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000']
    authorization:
      type: Bearer
      credentials_file: "/etc/prometheus/bearer.txt"
  - job_name: 'weather-event-handler'
    metrics_path: '/event-handler/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000']
    authorization:
      type: Bearer
      credentials_file: "/etc/prometheus/bearer.txt"
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:15692']
  - job_name: 'kong'
    static_configs:
      - targets: ['host.docker.internal:8001']